services:
  mail:
    image: analogic/poste.io
    container_name: poste
    restart: always
    hostname: mail
    domainname: holancloud.com
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      # ¡Esta es la línea más importante!
      - HTTPS=OFF
      - POSTEIO_HOSTNAME=mail.holancloud.com
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - maildata:/data
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poste.rule=Host(`mail.holancloud.com`)"
      - "traefik.http.routers.poste.entrypoints=websecure"
      - "traefik.http.routers.poste.tls=true"
      - "traefik.http.routers.poste.tls.certresolver=letsencrypt"
      - "traefik.http.services.poste.loadbalancer.server.port=80"

volumes:
  maildata:

networks:
  traefik_proxy:
    external: true
